# Generated by Django 6.0.3 on 2026-05-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_first_name_remove_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notify_by_default',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
