# Generated by Django 6.0.3 on 2026-03-25 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('released', models.DateField(blank=True, null=True, verbose_name='released')),
                ('rating', models.FloatField(default=0.0, verbose_name='rating')),
                ('image', models.URLField(blank=True, max_length=500, null=True, verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('domain', models.CharField(max_length=150, verbose_name='domain')),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='rating')),
                ('count', models.IntegerField(default=0, verbose_name='count')),
                ('percent', models.FloatField(default=0.0, verbose_name='percent')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_ratings', to='catalog.games')),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(max_length=100, verbose_name='Platform name')),
                ('minimum', models.TextField(blank=True, null=True, verbose_name='Minimum')),
                ('recommended', models.TextField(blank=True, null=True, verbose_name='Recommended')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='catalog.games')),
            ],
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(blank=True, max_length=500, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='catalog.games')),
            ],
        ),
        migrations.AddField(
            model_name='games',
            name='stores',
            field=models.ManyToManyField(blank=True, to='catalog.store', verbose_name='stores'),
        ),
    ]
