# Generated by Django 6.0.3 on 2026-03-25 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Requirement',
            new_name='Requirements',
        ),
        migrations.RenameModel(
            old_name='Screenshot',
            new_name='Screenshots',
        ),
        migrations.AddField(
            model_name='games',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='games',
            name='rating_count',
            field=models.IntegerField(default=0, verbose_name='Ratings count'),
        ),
    ]
