# Generated by Django 6.0.3 on 2026-03-27 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rename_requirement_requirements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='steam_id',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='GamePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('url', models.URLField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='catalog.games')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_prices', to='catalog.store')),
            ],
            options={
                'unique_together': {('game', 'store')},
            },
        ),
    ]
