# Generated by Django 6.0.3 on 2026-03-27 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_games_steam_id_gameprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameprice',
            name='retail_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='gameprice',
            name='savings',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
