# Generated by Django 6.0.3 on 2026-03-27 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_gameprice_retail_price_gameprice_savings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameprice',
            name='savings',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
