# Generated by Django 6.0.3 on 2026-03-27 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_gameprice_savings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameprice',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
