# Generated by Django 6.0.3 on 2026-03-31 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_gameprice_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='steam_id',
            field=models.CharField(blank=True, null=True),
        ),
    ]
