# Generated by Django 6.0.3 on 2026-04-01 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_genres_games_genres'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Games',
            new_name='Game',
        ),
        migrations.RenameModel(
            old_name='Genres',
            new_name='Genre',
        ),
        migrations.RenameModel(
            old_name='Ratings',
            new_name='Rating',
        ),
        migrations.RenameModel(
            old_name='Requirements',
            new_name='Requirement',
        ),
        migrations.RenameModel(
            old_name='Screenshots',
            new_name='Screenshot',
        ),
    ]
