# Generated by Django 6.0.3 on 2026-04-01 15:35

from django.db import migrations

from django.contrib.postgres.operations import TrigramExtension

class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_rename_games_game_rename_genres_genre_and_more'),
    ]

    operations = [
        TrigramExtension()
    ]
