# Generated by Django 6.0.3 on 2026-04-05 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20260401_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameprice',
            name='url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
