# Generated by Django 6.0.3 on 2026-04-07 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_platform_game_platform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='platform',
        ),
        migrations.AddField(
            model_name='game',
            name='platforms',
            field=models.ManyToManyField(blank=True, related_name='games', to='catalog.platform'),
        ),
        migrations.AlterField(
            model_name='game',
            name='genres',
            field=models.ManyToManyField(related_name='games', to='catalog.genre', verbose_name='genre'),
        ),
        migrations.AlterField(
            model_name='game',
            name='stores',
            field=models.ManyToManyField(blank=True, related_name='games', to='catalog.store', verbose_name='stores'),
        ),
    ]
