# Generated by Django 6.0.3 on 2026-04-07 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_remove_game_platform_game_platforms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
