# Generated by Django 6.0.3 on 2026-05-27 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_pricehistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricehistory',
            old_name='stores',
            new_name='store',
        ),
    ]
